version: '3.3'

services:

  server:
    restart: always
    command: /bin/sh -c "wait-for-it primarydb:5432 -- /bin/sh config/start-server.sh"

    build:
      context: ../user_watcher
      dockerfile: ../deploy/Dockerfile
    
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      DB_NAME: compose_primary_db
      DB_HOST: primarydb
      DB_USER: compose-postgres-user
      DB_PASSWORD: compose-postgres
      DB_PORT: 5432
    
    volumes:
      - ../user_watcher:/usr/src/app

    ports:
      - 8000:8000
      - 5678:5678
    
    depends_on:
      - primarydb

  primarydb:
    image: postgres:latest
    restart: always

    environment:
      POSTGRES_PASSWORD: compose-postgres
      POSTGRES_USER: compose-postgres-user
      POSTGRES_DB: compose_primary_db

    ports:
      - 32432:5432