# Generated by Django 4.2.9 on 2024-02-01 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, verbose_name='Ссылка, которую посещал пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_visit', models.DateTimeField(verbose_name='Дата визита')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('web_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited_web_resource', to='web_resources.webresource', verbose_name='Веб-ресурс')),
            ],
        ),
    ]
